### ISSUE TITLE
Petite question

### ISSUE THREAD

**Issue by Electronlibre2012** [xmow49/teleinfo-esphome-homeassistant#9]
Bonjour,

super boulot! 

j'ai un compteur classique avec la télé info L1 et L2 aussi, est ce que ca peux fonctionner stp?

Merci

Olivier

EDIT: merci j'ai trouvé un blog, la config est la même que ce soit linky ou compteur classique :)

**Comment by xmow49** [comment]
Slt,
Oui c'est la meme chose 😉
